<?php

namespace ScrapyardIO\Libraries\Displays\Drivers\SSD1306\Enums\CommandRegister;

enum SSD1306AddressingCommand: int
{
    case SET_LOW_COL_START_ADDRESS0 = 0x00;
    case SET_LOW_COL_START_ADDRESS1 = 0x01;
    case SET_LOW_COL_START_ADDRESS2 = 0x02;
    case SET_LOW_COL_START_ADDRESS3 = 0x03;
    case SET_LOW_COL_START_ADDRESS4 = 0x04;
    case SET_LOW_COL_START_ADDRESS5 = 0x05;
    case SET_LOW_COL_START_ADDRESS6 = 0x06;
    case SET_LOW_COL_START_ADDRESS7 = 0x07;
    case SET_LOW_COL_START_ADDRESS8 = 0x08;
    case SET_LOW_COL_START_ADDRESS9 = 0x09;
    case SET_LOW_COL_START_ADDRESS10 = 0x0A;
    case SET_LOW_COL_START_ADDRESS11 = 0x0B;
    case SET_LOW_COL_START_ADDRESS12 = 0x0C;
    case SET_LOW_COL_START_ADDRESS13 = 0x0D;
    case SET_LOW_COL_START_ADDRESS14 = 0x0E;
    case SET_LOW_COL_START_ADDRESS15 = 0x0F;

    case SET_HIGH_COL_START_ADDRESS0 = 0x10;
    case SET_HIGH_COL_START_ADDRESS1 = 0x11;
    case SET_HIGH_COL_START_ADDRESS2 = 0x12;
    case SET_HIGH_COL_START_ADDRESS3 = 0x13;
    case SET_HIGH_COL_START_ADDRESS4 = 0x14;
    case SET_HIGH_COL_START_ADDRESS5 = 0x15;
    case SET_HIGH_COL_START_ADDRESS6 = 0x16;
    case SET_HIGH_COL_START_ADDRESS7 = 0x17;
    case SET_HIGH_COL_START_ADDRESS8 = 0x18;
    case SET_HIGH_COL_START_ADDRESS9 = 0x19;
    case SET_HIGH_COL_START_ADDRESS10 = 0x1A;
    case SET_HIGH_COL_START_ADDRESS11 = 0x1B;
    case SET_HIGH_COL_START_ADDRESS12 = 0x1C;
    case SET_HIGH_COL_START_ADDRESS13 = 0x1D;
    case SET_HIGH_COL_START_ADDRESS14 = 0x1E;
    case SET_HIGH_COL_START_ADDRESS15 = 0x1F;

    case SET_MEMORY_ADDRESS_MODE = 0x20;
    case SET_COLUMN_RANGE = 0x21;
    case SET_PAGE_RANGE = 0x22;

    case SET_PAGE_START_ADDRESS0 = 0xB0;
    case SET_PAGE_START_ADDRESS1 = 0xB1;
    case SET_PAGE_START_ADDRESS2 = 0xB2;
    case SET_PAGE_START_ADDRESS3 = 0xB3;
    case SET_PAGE_START_ADDRESS4 = 0xB4;
    case SET_PAGE_START_ADDRESS5 = 0xB5;
    case SET_PAGE_START_ADDRESS6 = 0xB6;
    case SET_PAGE_START_ADDRESS7 = 0xB7;
}
